name: universal_disk_space
description: parses total and available disk spaces on Windows and Linux-based systems
version: 0.1.5
homepage: https://github.com/joaquimguimaraes/universal_disk_space
authors:
  - Gil Nóbrega <jgilfn@gmail.com>

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:

dev_dependencies: