name: universal_disk_space
description: parses total and available disk spaces on Windows and Linux-based systems
version: 0.1.21
homepage: https://github.com/joaquimguimaraes/universal_disk_space

environment:
  sdk: ">=2.12.0 <3.0.0"

# Or, if you just want `analysis_options.yaml`, it can be a dev dependency.
dev_dependencies:
  lints: ^1.0.1